# pdfQA document-summary retrieval benchmark

This notebook downloads 10 matched PDFs and annotation files from pdfQA, summarizes every PDF into one retrieval-oriented document summary, stores exactly one FastEmbed vector per PDF in PostgreSQL with pgvector, and measures whether each question retrieves its required PDF.

The main metric is document Recall@k. Each annotation names one required document, so a question is a hit when that document ID appears in the first k retrieved summaries. This evaluates document routing only, not answer correctness.

## Setup

From the repository directory, install the locked environment and start PostgreSQL:

    uv sync
    docker compose up -d pgvector

The default connection is postgresql+psycopg://langchain:langchain@localhost:6024/langchain. Override PGVECTOR_CONNECTION_STRING in .env when needed.

The summarizer provider matches notebook.ipynb. Set PROVIDER=ollama for local inference or PROVIDER=openrouter with an API key and model. Downloads, extracted text, and summaries are cached under artifacts/pdfqa, so interrupted runs can resume.

In [1]:
import hashlib
import json
import math
import os
import re
import time
import unicodedata
from pathlib import Path, PurePosixPath

import pandas as pd
import requests
from dotenv import load_dotenv
from huggingface_hub import HfApi, hf_hub_download

load_dotenv()

BENCHMARK_REPO = "pdfqa/pdfQA-Benchmark"
ANNOTATION_REPO = "pdfqa/pdfQA-Annotations"
CATEGORY = os.getenv("PDFQA_CATEGORY", "real-pdfQA")
DATASET_NAME = os.getenv("PDFQA_DATASET", "FeTaQA")
SAMPLE_SIZE = int(os.getenv("PDFQA_SAMPLE_SIZE", "10"))
RECALL_AT = tuple(sorted({int(k) for k in os.getenv("RECALL_AT", "1,3,5").split(",")}))

ARTIFACT_DIR = Path(os.getenv("PDFQA_ARTIFACT_DIR", "artifacts/pdfqa"))
PDF_DIR = ARTIFACT_DIR / "pdfs"
ANNOTATION_DIR = ARTIFACT_DIR / "annotations"
TEXT_DIR = ARTIFACT_DIR / "text"
SUMMARY_DIR = ARTIFACT_DIR / "summaries"
for directory in (PDF_DIR, ANNOTATION_DIR, TEXT_DIR, SUMMARY_DIR):
    directory.mkdir(parents=True, exist_ok=True)

print(f"Subset: {CATEGORY}/{DATASET_NAME}")
print(f"Documents: {SAMPLE_SIZE}; Recall cutoffs: {RECALL_AT}")

Subset: real-pdfQA/FeTaQA
Documents: 10; Recall cutoffs: (1, 3, 5)

## Select matched PDFs and annotations

The annotation repository contains heterogeneous JSON schemas, which currently prevents loading the whole repository through the datasets viewer. Listing files through huggingface_hub is more reliable here. A document is matched by its filename stem inside the same category and dataset.

In [2]:
api = HfApi()
benchmark_files = api.list_repo_files(BENCHMARK_REPO, repo_type="dataset")
annotation_files = api.list_repo_files(ANNOTATION_REPO, repo_type="dataset")

pdf_prefix = f"{CATEGORY}/01.2_Input_Files_PDF/{DATASET_NAME}/"
annotation_prefix = f"{CATEGORY}/{DATASET_NAME}/"

pdf_by_id = {
    PurePosixPath(path).stem: path
    for path in benchmark_files
    if path.startswith(pdf_prefix) and path.lower().endswith(".pdf")
}
annotation_by_id = {
    PurePosixPath(path).stem: path
    for path in annotation_files
    if path.startswith(annotation_prefix) and path.lower().endswith(".json")
}

matched_ids = sorted(set(pdf_by_id) & set(annotation_by_id), key=str.casefold)
if len(matched_ids) < SAMPLE_SIZE:
    raise ValueError(
        f"Requested {SAMPLE_SIZE} documents, but only {len(matched_ids)} matched in "
        f"{CATEGORY}/{DATASET_NAME}."
    )

# The sorted slice is deterministic, which keeps benchmark comparisons reproducible.
sample_ids = matched_ids[:SAMPLE_SIZE]
manifest = pd.DataFrame({
    "document_id": sample_ids,
    "pdf_repo_path": [pdf_by_id[doc_id] for doc_id in sample_ids],
    "annotation_repo_path": [annotation_by_id[doc_id] for doc_id in sample_ids],
})
print(f"Found {len(matched_ids)} matched documents; selected {len(manifest)}.")
manifest

Found 65 matched documents; selected 10.

,document_id,pdf_repo_path,annotation_repo_path
0,2002 FIFA World Cup,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/2002 FI...,real-pdfQA/FeTaQA/2002 FIFA World Cup.json
1,2017 Ohio State Buckeyes football team,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/2017 Oh...,real-pdfQA/FeTaQA/2017 Ohio State Buckeyes foo...
2,2018 Australian Grand Prix,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/2018 Au...,real-pdfQA/FeTaQA/2018 Australian Grand Prix.json
3,2018 Indianapolis 500,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/2018 In...,real-pdfQA/FeTaQA/2018 Indianapolis 500.json
4,A View from the Bridge,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/A View ...,real-pdfQA/FeTaQA/A View from the Bridge.json
5,Adam Pascal,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/Adam Pa...,real-pdfQA/FeTaQA/Adam Pascal.json
6,Andra Day,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/Andra D...,real-pdfQA/FeTaQA/Andra Day.json
7,Coins of the United States dollar,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/Coins o...,real-pdfQA/FeTaQA/Coins of the United States d...
8,Colleen Ballinger,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/Colleen...,real-pdfQA/FeTaQA/Colleen Ballinger.json
9,Courteney Cox,real-pdfQA/01.2_Input_Files_PDF/FeTaQA/Courten...,real-pdfQA/FeTaQA/Courteney Cox.json

In [3]:
def download_dataset_file(repo_id: str, repo_path: str, local_dir: Path) -> Path:
    return Path(hf_hub_download(
        repo_id=repo_id,
        repo_type="dataset",
        filename=repo_path,
        local_dir=local_dir,
    ))

downloaded_rows = []
for row in manifest.itertuples(index=False):
    started = time.perf_counter()
    pdf_path = download_dataset_file(BENCHMARK_REPO, row.pdf_repo_path, PDF_DIR)
    annotation_path = download_dataset_file(ANNOTATION_REPO, row.annotation_repo_path, ANNOTATION_DIR)
    downloaded_rows.append({
        **row._asdict(),
        "pdf_path": str(pdf_path),
        "annotation_path": str(annotation_path),
        "download_seconds": time.perf_counter() - started,
        "pdf_megabytes": pdf_path.stat().st_size / 1_000_000,
    })

manifest = pd.DataFrame(downloaded_rows)
manifest[["document_id", "pdf_megabytes", "download_seconds"]]

                              document_id  pdf_megabytes  download_seconds
0                     2002 FIFA World Cup       2.614254          0.636694
1  2017 Ohio State Buckeyes football team       2.343657          0.760699
2              2018 Australian Grand Prix       1.136305          0.622491
3                   2018 Indianapolis 500       2.450729          0.669971
4                  A View from the Bridge       0.666206          0.682105
5                             Adam Pascal       0.570210          0.726909
6                               Andra Day       0.616070          0.670811
7       Coins of the United States dollar       0.874834          0.831552
8                       Colleen Ballinger       1.553172          0.662671
9                           Courteney Cox       1.069181          0.717830

## Configure the summarizer

PDFs are converted to Markdown with Docling, split on tokenizer boundaries, summarized chunk by chunk, and reduced until one summary remains. Only that final summary is embedded. The prompt keeps distinctive names, dates, terminology, and facts because those features help document retrieval.

In [4]:
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from langchain_openrouter import ChatOpenRouter
from transformers import AutoTokenizer

PROVIDER = os.getenv("PROVIDER", "openrouter").strip().lower()
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "LiquidAI/lfm2.5-2.6b:q4_k_m")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "liquid/lfm-2.5-2.6b:free").strip()
TOKENIZER_NAME = os.getenv("TOKENIZER_NAME", "LiquidAI/LFM2.5-2.6B")
OLLAMA_BASE_URL = os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434").rstrip("/")
CONTEXT_LENGTH = int(os.getenv("OLLAMA_NUM_CTX", "32768"))
MAX_OUTPUT_TOKENS = int(os.getenv("MAX_OUTPUT_TOKENS", "1024"))
SUMMARY_CHUNK_TOKENS = int(os.getenv("SUMMARY_CHUNK_TOKENS", "12000"))
SUMMARY_PROMPT_VERSION = 1

tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_NAME, trust_remote_code=True)

if PROVIDER == "ollama":
    response = requests.get(f"{OLLAMA_BASE_URL}/api/tags", timeout=10)
    response.raise_for_status()
    installed_models = {item["name"] for item in response.json().get("models", [])}
    if OLLAMA_MODEL not in installed_models:
        raise RuntimeError(f"{OLLAMA_MODEL} is not installed. Run: ollama pull {OLLAMA_MODEL}")
    model = ChatOllama(
        model=OLLAMA_MODEL,
        base_url=OLLAMA_BASE_URL,
        validate_model_on_init=True,
        reasoning=False,
        num_gpu=0,
        num_ctx=CONTEXT_LENGTH,
        num_predict=MAX_OUTPUT_TOKENS,
        temperature=0.1,
    )
    MODEL_NAME = OLLAMA_MODEL
elif PROVIDER == "openrouter":
    if not os.getenv("OPENROUTER_API_KEY") or not OPENROUTER_MODEL:
        raise RuntimeError("OPENROUTER_API_KEY and OPENROUTER_MODEL are required for OpenRouter.")
    model = ChatOpenRouter(
        model=OPENROUTER_MODEL,
        max_tokens=MAX_OUTPUT_TOKENS,
        temperature=0.1,
    )
    MODEL_NAME = OPENROUTER_MODEL
else:
    raise ValueError("PROVIDER must be either 'ollama' or 'openrouter'.")

print(f"Provider: {PROVIDER}; model: {MODEL_NAME}; chunk limit: {SUMMARY_CHUNK_TOKENS:,} tokens")

d:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\langchain_core\utils\pydantic.py:42: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1 import BaseModel as BaseModelV1

Provider: openrouter; model: liquid/lfm-2.5-2.6b:free; chunk limit: 12,000 tokens

In [5]:
SYSTEM_PROMPT = "You are a careful document summarizer. Use only the supplied document text."

def count_tokens(text: str) -> int:
    return len(tokenizer.encode(text, add_special_tokens=False))

def split_by_tokens(text: str, max_tokens: int) -> list[str]:
    token_ids = tokenizer.encode(text, add_special_tokens=False)
    return [
        tokenizer.decode(token_ids[start:start + max_tokens], skip_special_tokens=True)
        for start in range(0, len(token_ids), max_tokens)
    ] or [""]

def response_text(content) -> str:
    if isinstance(content, str):
        return content.strip()
    if isinstance(content, list):
        return "".join(
            block.get("text", "") if isinstance(block, dict) else str(block)
            for block in content
        ).strip()
    return str(content).strip()

def invoke_summary(prompt: str) -> tuple[str, dict]:
    input_tokens = count_tokens(SYSTEM_PROMPT) + count_tokens(prompt)
    if PROVIDER == "ollama" and input_tokens + MAX_OUTPUT_TOKENS > CONTEXT_LENGTH:
        raise ValueError(
            f"Summary request needs about {input_tokens + MAX_OUTPUT_TOKENS:,} tokens, "
            f"but OLLAMA_NUM_CTX is {CONTEXT_LENGTH:,}."
        )

    started = time.perf_counter()
    response = model.invoke([
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ])
    elapsed = time.perf_counter() - started
    output = response_text(response.content)
    usage = response.usage_metadata or {}
    measured_input = int(usage.get("input_tokens") or input_tokens)
    measured_output = int(usage.get("output_tokens") or count_tokens(output))
    return output, {
        "calls": 1,
        "input_tokens": measured_input,
        "output_tokens": measured_output,
        "elapsed_seconds": elapsed,
        "output_tokens_per_second": measured_output / elapsed if elapsed else math.nan,
    }

def add_metrics(total: dict, part: dict) -> None:
    for key in ("calls", "input_tokens", "output_tokens", "elapsed_seconds"):
        total[key] += part[key]

In [6]:
from docling.document_converter import DocumentConverter

converter = DocumentConverter()

def cache_path(directory: Path, document_id: str, suffix: str) -> Path:
    digest = hashlib.sha1(document_id.encode("utf-8")).hexdigest()
    return directory / f"{digest}{suffix}"

def extract_pdf(document_id: str, pdf_path: Path) -> tuple[str, dict]:
    text_path = cache_path(TEXT_DIR, document_id, ".md")
    if text_path.exists():
        text = text_path.read_text(encoding="utf-8")
        return text, {"extract_seconds": 0.0, "extract_cached": True}

    started = time.perf_counter()
    text = converter.convert(source=str(pdf_path)).document.export_to_markdown()
    elapsed = time.perf_counter() - started
    if not text.strip():
        raise ValueError(f"No text was extracted from {pdf_path}")
    text_path.write_text(text, encoding="utf-8")
    return text, {"extract_seconds": elapsed, "extract_cached": False}

MAP_PROMPT = """Summarize this part of the document titled {title} for semantic document retrieval.
Preserve the main subject, distinctive named entities, dates, terminology, and important facts that a user may mention in a question.
Write a dense, factual summary. Do not refer to chunks or these instructions.

DOCUMENT TEXT:
{text}"""

REDUCE_PROMPT = """Combine these partial summaries of the document titled {title} into one coherent summary for semantic document retrieval.
Preserve the main subject, distinctive named entities, dates, terminology, and important facts. Remove repetition.
Return only the summary.

PARTIAL SUMMARIES:
{text}"""

def summarize_document(document_id: str, text: str) -> tuple[str, dict]:
    summary_path = cache_path(SUMMARY_DIR, document_id, ".json")
    signature = {
        "provider": PROVIDER,
        "model": MODEL_NAME,
        "tokenizer": TOKENIZER_NAME,
        "chunk_tokens": SUMMARY_CHUNK_TOKENS,
        "prompt_version": SUMMARY_PROMPT_VERSION,
    }
    if summary_path.exists():
        cached = json.loads(summary_path.read_text(encoding="utf-8"))
        if cached.get("signature") == signature:
            metrics = cached["metrics"] | {"summary_cached": True}
            return cached["summary"], metrics

    totals = {"calls": 0, "input_tokens": 0, "output_tokens": 0, "elapsed_seconds": 0.0}
    partials = []
    for chunk in split_by_tokens(text, SUMMARY_CHUNK_TOKENS):
        summary, metrics = invoke_summary(MAP_PROMPT.format(title=document_id, text=chunk))
        partials.append(summary)
        add_metrics(totals, metrics)

    while len(partials) > 1:
        combined = "\n\n".join(partials)
        groups = split_by_tokens(combined, SUMMARY_CHUNK_TOKENS)
        reduced = []
        for group in groups:
            summary, metrics = invoke_summary(REDUCE_PROMPT.format(title=document_id, text=group))
            reduced.append(summary)
            add_metrics(totals, metrics)
        partials = reduced

    final_summary = partials[0]
    totals["output_tokens_per_second"] = (
        totals["output_tokens"] / totals["elapsed_seconds"] if totals["elapsed_seconds"] else math.nan
    )
    totals["summary_cached"] = False
    summary_path.write_text(json.dumps({
        "document_id": document_id,
        "signature": signature,
        "summary": final_summary,
        "metrics": {key: value for key, value in totals.items() if key != "summary_cached"},
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    return final_summary, totals

## Extract and summarize the sample

This is the slow section, especially with CPU-only Ollama. Each completed document is cached immediately.

In [ ]:
document_rows = []
for position, row in enumerate(manifest.itertuples(index=False), start=1):
    print(f"[{position}/{len(manifest)}] {row.document_id}")
    text, extract_metrics = extract_pdf(row.document_id, Path(row.pdf_path))
    source_tokens = count_tokens(text)
    summary, summary_metrics = summarize_document(row.document_id, text)
    summary_tokens = count_tokens(summary)
    document_rows.append({
        **row._asdict(),
        **extract_metrics,
        **{f"summary_{key}": value for key, value in summary_metrics.items()},
        "source_tokens": source_tokens,
        "summary_tokens": summary_tokens,
        "compression_ratio": source_tokens / max(summary_tokens, 1),
        "token_reduction_percent": 100 * (1 - summary_tokens / max(source_tokens, 1)),
        "summary": summary,
    })

documents_df = pd.DataFrame(document_rows)

[1/10] 2002 FIFA World Cup

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

[INFO] 2026-10-14 15:29:06,975 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-10-14 15:29:07,114 [RapidOCR] download_file.py:60: File exists and is valid: D:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\rapidocr\models\PP-OCRv6_det_small.onnx
[INFO] 2026-10-14 15:29:07,115 [RapidOCR] main.py:63: Using D:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\rapidocr\models\PP-OCRv6_det_small.onnx
[INFO] 2026-10-14 15:29:08,315 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-10-14 15:29:08,360 [RapidOCR] download_file.py:60: File exists and is valid: D:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-10-14 15:29:08,362 [RapidOCR] main.py:63: Using D:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-10-14 15:29:08,513 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-10-14 15:29:08,565 [RapidOCR] download_file.py:60: File exists and is valid: D:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\rapidocr\models\PP-OCRv6_rec_small.onnx
[INFO] 2026-10-14 15:29:08,566 [RapidOCR] main.py:63: Using D:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\rapidocr\models\PP-OCRv6_rec_small.onnx

[2/10] 2017 Ohio State Buckeyes football team

d:\Workspace\Repository\llm-summarization\.venv\Lib\site-packages\docling_core\types\doc\document.py:326: UserWarning: Table cell bbox coordinate l on page 3 is outside page bounds: value=-191.53843263536692 < lo=0.0; clamping to 0.0
  cell.bbox = self._clamp_bbox_to_page(

[3/10] 2018 Australian Grand Prix

RapidOCR returned empty result!

[4/10] 2018 Indianapolis 500
[5/10] A View from the Bridge
[6/10] Adam Pascal
[7/10] Andra Day

RapidOCR returned empty result!

[8/10] Coins of the United States dollar
2026-10-14 15:38:03,229 MatchingPostProcessor WARNING  1 of 116 pdf cells matched neither a row nor a column band of the 6x11 grid and were dropped from the table
[9/10] Colleen Ballinger
[10/10] Courteney Cox

RapidOCR returned empty result!

KeyError: "['summary_cached'] not in index"

In [8]:
documents_df[[
    "document_id", "source_tokens", "summary_tokens", "compression_ratio",
    "token_reduction_percent", "summary_output_tokens_per_second",
]]

,document_id,source_tokens,summary_tokens,compression_ratio,token_reduction_percent,summary_output_tokens_per_second
0,2002 FIFA World Cup,26234,518,50.644788,98.025463,186.018663
1,2017 Ohio State Buckeyes football team,33868,620,54.625806,98.169363,224.580129
2,2018 Australian Grand Prix,11601,662,17.524169,94.293595,197.093400
3,2018 Indianapolis 500,23372,477,48.997904,97.959096,194.135874
4,A View from the Bridge,7607,366,20.784153,95.188642,167.163476
5,Adam Pascal,7393,555,13.320721,92.492899,189.328673
6,Andra Day,5905,414,14.263285,92.988992,197.320955
7,Coins of the United States dollar,6011,821,7.321559,86.341707,203.884103
8,Colleen Ballinger,28859,536,53.841418,98.142694,224.433719
9,Courteney Cox,11147,506,22.029644,95.460662,202.441155

In [9]:
BASELINE_CHUNK_TOKENS = int(os.getenv("BASELINE_CHUNK_TOKENS", "512"))
baseline_vectors = int(sum(math.ceil(tokens / BASELINE_CHUNK_TOKENS) for tokens in documents_df.source_tokens))
summary_vectors = len(documents_df)
compression_metrics = pd.Series({
    "documents": len(documents_df),
    "source_tokens": int(documents_df.source_tokens.sum()),
    "summary_tokens": int(documents_df.summary_tokens.sum()),
    "weighted_token_reduction_percent": 100 * (
        1 - documents_df.summary_tokens.sum() / documents_df.source_tokens.sum()
    ),
    "mean_compression_ratio": documents_df.compression_ratio.mean(),
    "estimated_vectors_with_512_token_chunks": baseline_vectors,
    "vectors_with_one_summary_per_document": summary_vectors,
    "estimated_vector_reduction_percent": 100 * (1 - summary_vectors / baseline_vectors),
    "summarization_wall_output_tokens_per_second": (
        documents_df.summary_output_tokens.sum() / documents_df.summary_elapsed_seconds.sum()
        if documents_df.summary_elapsed_seconds.sum() else math.nan
    ),
})
compression_metrics.to_frame("value")

                                                     value
documents                                        10.000000
source_tokens                                161997.000000
summary_tokens                                 5475.000000
weighted_token_reduction_percent                 96.620308
mean_compression_ratio                           30.335345
estimated_vectors_with_512_token_chunks         321.000000
vectors_with_one_summary_per_document            10.000000
estimated_vector_reduction_percent               96.884735
summarization_wall_output_tokens_per_second     204.270563

## Embed one summary per document and index it in pgvector

The adapter uses FastEmbed passage embeddings for document summaries and query embeddings for questions. Timing records approximate tokenizer tokens per second, texts per second, and wall time. RESET_COLLECTION defaults to true so stale documents cannot affect a benchmark rerun.

In [10]:
from fastembed import TextEmbedding
from langchain_core.documents import Document
from langchain_core.embeddings import Embeddings
from langchain_postgres import PGVector

FASTEMBED_MODEL = os.getenv("FASTEMBED_MODEL", "BAAI/bge-small-en-v1.5")
FASTEMBED_THREADS = int(os.getenv("FASTEMBED_THREADS", str(max(1, (os.cpu_count() or 2) // 2))))
PGVECTOR_CONNECTION_STRING = os.getenv(
    "PGVECTOR_CONNECTION_STRING",
    "postgresql+psycopg://langchain:langchain@localhost:6024/langchain",
)
COLLECTION_NAME = os.getenv("PGVECTOR_COLLECTION", "pdfqa_document_summaries")
RESET_COLLECTION = os.getenv("RESET_COLLECTION", "true").lower() == "true"

class MeasuredFastEmbedEmbeddings(Embeddings):
    def __init__(self, model_name: str, threads: int):
        self.model = TextEmbedding(
            model_name=model_name,
            threads=threads,
            cache_dir=str(ARTIFACT_DIR / "fastembed_cache"),
        )
        self.document_measurements = []
        self.query_measurements = []

    def _measure(self, texts: list[str], method, sink: list[dict]) -> list[list[float]]:
        started = time.perf_counter()
        vectors = [vector.tolist() for vector in method(texts)]
        elapsed = time.perf_counter() - started
        tokens = sum(count_tokens(text) for text in texts)
        sink.append({
            "texts": len(texts),
            "tokens": tokens,
            "elapsed_seconds": elapsed,
            "texts_per_second": len(texts) / elapsed if elapsed else math.nan,
            "tokens_per_second": tokens / elapsed if elapsed else math.nan,
        })
        return vectors

    def embed_documents(self, texts: list[str]) -> list[list[float]]:
        return self._measure(texts, self.model.passage_embed, self.document_measurements)

    def embed_query(self, text: str) -> list[float]:
        return self._measure([text], self.model.query_embed, self.query_measurements)[0]

embeddings = MeasuredFastEmbedEmbeddings(FASTEMBED_MODEL, FASTEMBED_THREADS)
vector_store = PGVector(
    embeddings=embeddings,
    collection_name=COLLECTION_NAME,
    connection=PGVECTOR_CONNECTION_STRING,
    use_jsonb=True,
    pre_delete_collection=RESET_COLLECTION,
)

index_documents = [
    Document(
        page_content=row.summary,
        metadata={
            "document_id": row.document_id,
            "category": CATEGORY,
            "dataset": DATASET_NAME,
            "pdf_repo_path": row.pdf_repo_path,
        },
    )
    for row in documents_df.itertuples(index=False)
]

index_started = time.perf_counter()
indexed_ids = vector_store.add_documents(index_documents, ids=sample_ids)
index_seconds = time.perf_counter() - index_started
assert len(indexed_ids) == len(sample_ids) == len(set(indexed_ids))
print(f"Indexed {len(indexed_ids)} summaries as {len(indexed_ids)} vectors in {index_seconds:.2f}s.")

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Collection not found

Indexed 10 summaries as 10 vectors in 4.05s.

## Load ground-truth questions and evaluate retrieval

Every selected annotation file contributes all of its questions. The required document comes from file_name, with the annotation filename used as a fallback. IDs are normalized only for comparison.

In [11]:
def normalize_document_id(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", str(value))
    return re.sub(r"\s+", " ", normalized).strip().casefold()

question_rows = []
for row in manifest.itertuples(index=False):
    payload = json.loads(Path(row.annotation_path).read_text(encoding="utf-8"))
    records = payload if isinstance(payload, list) else payload.get("data", [payload])
    for question_index, record in enumerate(records):
        question = str(record.get("question", "")).strip()
        if not question:
            continue
        required_id = str(record.get("file_name") or row.document_id)
        question_rows.append({
            "question_id": f"{row.document_id}::{question_index}",
            "question": question,
            "required_document_id": required_id,
        })

questions_df = pd.DataFrame(question_rows)
print(f"Loaded {len(questions_df)} questions for {questions_df.required_document_id.nunique()} documents.")
questions_df.head()

Loaded 10 questions for 10 documents.

,question_id,question,required_document_id
0,2002 FIFA World Cup::0,What were the results of the FIFA World Cup ma...,2002 FIFA World Cup
1,2017 Ohio State Buckeyes football team::0,How many yards did Dobbins rush and J.T. Barre...,2017 Ohio State Buckeyes football team
2,2018 Australian Grand Prix::0,What was Lewis Hamilton’s fastest lap in the 2...,2018 Australian Grand Prix
3,2018 Indianapolis 500::0,What driver had the fastest speed at the 2018 ...,2018 Indianapolis 500
4,A View from the Bridge::0,"Which categories of Tony Awards did ""A View fr...",A View from the Bridge

In [12]:
max_k = min(max(RECALL_AT), len(index_documents))
retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": max_k})

retrieval_rows = []
evaluation_started = time.perf_counter()
for row in questions_df.itertuples(index=False):
    started = time.perf_counter()
    retrieved = retriever.invoke(row.question)
    latency = time.perf_counter() - started
    retrieved_ids = [str(doc.metadata["document_id"]) for doc in retrieved]
    normalized_required = normalize_document_id(row.required_document_id)
    normalized_retrieved = [normalize_document_id(doc_id) for doc_id in retrieved_ids]
    rank = next(
        (position for position, doc_id in enumerate(normalized_retrieved, start=1) if doc_id == normalized_required),
        None,
    )
    result = {
        **row._asdict(),
        "retrieved_document_ids": retrieved_ids,
        "rank": rank,
        "reciprocal_rank": 1 / rank if rank else 0.0,
        "latency_ms": latency * 1000,
    }
    for k in RECALL_AT:
        result[f"hit_at_{k}"] = bool(rank and rank <= min(k, max_k))
    retrieval_rows.append(result)

evaluation_seconds = time.perf_counter() - evaluation_started
results_df = pd.DataFrame(retrieval_rows)
results_df[[
    "question", "required_document_id", "retrieved_document_ids", "rank", "latency_ms",
    *[f"hit_at_{k}" for k in RECALL_AT],
]]

,question,required_document_id,retrieved_document_ids,rank,latency_ms,hit_at_1,hit_at_3,hit_at_5
0,What were the results of the FIFA World Cup ma...,2002 FIFA World Cup,"[2002 FIFA World Cup, 2018 Australian Grand Pr...",1,224.5574,True,True,True
1,How many yards did Dobbins rush and J.T. Barre...,2017 Ohio State Buckeyes football team,"[2017 Ohio State Buckeyes football team, 2018 ...",1,113.9874,True,True,True
2,What was Lewis Hamilton’s fastest lap in the 2...,2018 Australian Grand Prix,"[2018 Australian Grand Prix, 2018 Indianapolis...",1,92.2656,True,True,True
3,What driver had the fastest speed at the 2018 ...,2018 Indianapolis 500,"[2018 Indianapolis 500, 2018 Australian Grand ...",1,79.0329,True,True,True
4,"Which categories of Tony Awards did ""A View fr...",A View from the Bridge,"[A View from the Bridge, Adam Pascal, 2018 Ind...",1,69.4457,True,True,True
5,What roles and shows did Adam Pascal perform w...,Adam Pascal,"[Adam Pascal, Colleen Ballinger, Courteney Cox...",1,38.4963,True,True,True
6,What awards was Andra Day nominated for in 201...,Andra Day,"[Andra Day, Colleen Ballinger, Courteney Cox, ...",1,59.7397,True,True,True
7,Which circulated United States coins were issu...,Coins of the United States dollar,"[Coins of the United States dollar, 2017 Ohio ...",1,70.9261,True,True,True
8,What roles did Colleen Ballinger play in 2013?,Colleen Ballinger,"[Colleen Ballinger, Courteney Cox, Adam Pascal...",1,56.7986,True,True,True
9,What role did Courteney Cox play in the Scream...,Courteney Cox,"[Courteney Cox, Colleen Ballinger, Adam Pascal...",1,46.1436,True,True,True

In [13]:
document_embedding = pd.DataFrame(embeddings.document_measurements)
query_embedding = pd.DataFrame(embeddings.query_measurements)

metrics = {
    "documents": len(index_documents),
    "vectors": len(indexed_ids),
    "questions": len(results_df),
    **{f"recall_at_{k}": results_df[f"hit_at_{k}"].mean() for k in RECALL_AT},
    "mean_reciprocal_rank": results_df.reciprocal_rank.mean(),
    "mean_retrieval_latency_ms": results_df.latency_ms.mean(),
    "retrieval_queries_per_second": len(results_df) / evaluation_seconds,
    "indexing_documents_per_second": len(index_documents) / index_seconds,
    "document_embedding_tokens_per_second_approx": (
        document_embedding.tokens.sum() / document_embedding.elapsed_seconds.sum()
    ),
    "query_embedding_tokens_per_second_approx": (
        query_embedding.tokens.sum() / query_embedding.elapsed_seconds.sum()
    ),
    "source_to_summary_token_reduction_percent": compression_metrics[
        "weighted_token_reduction_percent"
    ],
    "estimated_vector_reduction_percent": compression_metrics[
        "estimated_vector_reduction_percent"
    ],
}

metrics_df = pd.Series(metrics, name="value").to_frame()
metrics_df

                                                   value
documents                                      10.000000
vectors                                        10.000000
questions                                      10.000000
recall_at_1                                     1.000000
recall_at_3                                     1.000000
recall_at_5                                     1.000000
mean_reciprocal_rank                            1.000000
mean_retrieval_latency_ms                      85.139330
retrieval_queries_per_second                   11.647121
indexing_documents_per_second                   2.470341
document_embedding_tokens_per_second_approx  1602.094691
query_embedding_tokens_per_second_approx      473.739361
source_to_summary_token_reduction_percent      96.620308
estimated_vector_reduction_percent             96.884735

## Interpreting and scaling the benchmark

Recall@k answers only whether the correct PDF was routed into the candidate set. It does not show whether the summary retained enough detail to answer the question.

To scale up, increase PDFQA_SAMPLE_SIZE. The summarization and extraction caches make reruns incremental. Keep one summary per document for the experimental condition, and compare it with a separate chunked baseline if you want to quantify the retrieval quality tradeoff. The estimated vector reduction uses 512-token source chunks as that baseline and does not create those vectors.